version: '3.7'
services:
  mongodb:
    container_name: "db_mongo_dev"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app_network

  trema:
    container_name: trema
    build: 
      context: .
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data_container:
