{
 "title": "Trema",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requête à /odyssee",
   "type": "timeseries",
   "description": "Le nombre de requête faites à odyssee",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "trema_odyssee_cmd_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requête à /secret",
   "type": "timeseries",
   "description": "Le nombre de requête faites à secret",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "trema_secret_cmd_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requête reçu par Calidum-Rotae",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "trema_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "POST /webhooks errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "trema_http_errors_total", "legendFormat": "__auto" }
   ]
  }
 ]
}