name: Docker

on:
  push:
    branches:
      - master

env:
  MONGO_USER: "root"
  MONGO_PASSWORD: "root"
  MONGO_HOST: "localhost"
  MONGO_PORT: 27017

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start containers
        run: docker-compose -f "tests/docker-compose.yml" up -d

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          python -m pytest -v

  build-push-ghcr:
    needs: test
    uses:
      ClubCedille/cedille-workflows/.github/workflows/build-push-ghcr.yaml@master
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit